# Analogous file in Polars for reference:
# https://github.com/pola-rs/polars/blob/main/rust-toolchain.toml
[toolchain]
channel = "nightly-2025-10-24"
components = ["rustfmt", "clippy"]
profile = "minimal"
