name: Elixir CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  EXPLORER_BUILD: true
  RUST_TOOLCHAIN_VERSION: nightly-2023-02-14
  MIX_ENV: test

jobs:
  test:
    strategy:
      matrix:
        include:
          # - otp_version: 25.3
          #   elixir_version: 1.14

          - otp_version: 26.0
            elixir_version: "1.15.0-rc.1"

    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            _build/test/lib/explorer/native/explorer
            ~/.cargo
          key: native-${{ runner.os }}-${{ env.RUST_TOOLCHAIN_VERSION }}-${{ hashFiles('native/**/Cargo.lock') }}
          restore-keys: |
            native-${{ runner.os }}

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "${{ env.RUST_TOOLCHAIN_VERSION }}"

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp_version }}
          elixir-version: ${{ matrix.elixir_version }}

      - run: mix deps.get
      - run: mix deps.compile
      - name: Run tests
        run: mix test --warnings-as-errors
      - name: Compile once again but without optional deps
        run: mix compile --force --warnings-as-errors --no-optional-deps

  format:
    runs-on: ubuntu-latest
    name: mix format
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26.0
          elixir-version: 1.14
      - run: mix format --check-formatted
