name: Elixir CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  EXPLORER_BUILD: true
  MIX_ENV: test

jobs:
  test:
    strategy:
      matrix:
        include:
          - otp_version: 25.3
            elixir_version: 1.14

          - otp_version: "26.2.1"
            elixir_version: 1.16

    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v4

      # - uses: actions/cache@v3
      #   with:
      #     path: |
      #       _build/test/lib/explorer/native/explorer
      #       ~/.cargo/bin/
      #       ~/.cargo/registry/index/
      #       ~/.cargo/registry/cache/
      #       ~/.cargo/git/db/
      #     key: test-native-${{ runner.os }}-${{ hashFiles('native/**/Cargo.lock') }}
      #     restore-keys: |
      #       test-native-${{ runner.os }}

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp_version }}
          elixir-version: ${{ matrix.elixir_version }}

      - run: mix deps.get
      - run: mix deps.compile
      - name: Run tests
        run: mix test --warnings-as-errors
      - name: Run property tests
        run: |
          mix test --only property --warnings-as-errors
      - name: Compile once again but without optional deps
        run: mix compile --force --warnings-as-errors --no-optional-deps
      - name: Run cloud integration tests
        run: |
          mix localstack.setup
          mix test --only cloud_integration

  format:
    runs-on: ubuntu-latest
    name: mix format
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.2.1"
          elixir-version: 1.16
      - run: mix format --check-formatted
