name: Precomp NIFs

on:
  push:
    branches:
      - main
    paths:
      # Just run on main branch if "native" path changed.
      - "native/**"
      # Also run if this file changes.
      - ".github/workflows/release.yml"
    tags:
      # Tags will always run.
      - "*"
  pull_request:
    paths:
      # In PRs we only run if this file changes.
      - ".github/workflows/release.yml"
  workflow_dispatch:

jobs:
  build_release:
    name: NIF ${{ matrix.nif }} - ${{ matrix.job.target }} (${{ matrix.job.os }} | ${{ matrix.job.variant || 'default' }})
    runs-on: ${{ matrix.job.os }}

    permissions:
      contents: write
      id-token: write
      attestations: write

    strategy:
      fail-fast: false
      matrix:
        nif: ["2.15"]
        job:
          - { target: aarch64-apple-darwin, os: macos-11 }
          - { target: aarch64-unknown-linux-gnu, os: ubuntu-20.04, use-cross: true }
          - { target: aarch64-unknown-linux-musl, os: ubuntu-20.04, use-cross: true }
          - { target: x86_64-apple-darwin, os: macos-11 }
          - { target: x86_64-pc-windows-gnu, os: windows-2022, rustflags: "-C target-feature=+fxsr,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+fma" }
          - { target: x86_64-pc-windows-gnu, os: windows-2022, variant: "legacy_cpu" }
          - { target: x86_64-pc-windows-msvc, os: windows-2019, rustflags: "-C target-feature=+fxsr,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+fma" }
          - { target: x86_64-pc-windows-msvc, os: windows-2019, variant: "legacy_cpu" }
          - { target: x86_64-unknown-freebsd, os: ubuntu-22.04, use-cross: true, rustflags: "-C target-feature=+fxsr,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+fma" }
          - { target: x86_64-unknown-freebsd, os: ubuntu-22.04, use-cross: true, variant: "legacy_cpu" }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-20.04, rustflags: "-C target-feature=+fxsr,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+fma" }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-20.04, variant: "legacy_cpu" }
          - { target: x86_64-unknown-linux-musl, os: ubuntu-20.04, use-cross: true }

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Extract crate information
        shell: bash
        run: |
          # Get the project version from mix.exs
          echo "PROJECT_VERSION=$(sed -n 's/^  @version "\(.*\)"/\1/p' mix.exs | head -n1)" >> $GITHUB_ENV

      - name: Maybe add Rust flags for compilation
        shell: bash
        run: |
          echo "RUSTFLAGS=${{ matrix.job.rustflags }}" >> $GITHUB_ENV
        if: ${{ matrix.job.rustflags }}

      - name: Add target
        shell: bash
        run: |
          rustup target add ${{ matrix.job.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v0-precomp
          shared-key: ${{ matrix.job.target }}-${{ matrix.nif }}
          workspaces: |
            native/explorer

      - name: Build the project
        id: build-crate
        uses: philss/rustler-precompiled-action@v1.1.4
        with:
          project-name: explorer
          project-version: ${{ env.PROJECT_VERSION }}
          target: ${{ matrix.job.target }}
          nif-version: ${{ matrix.nif }}
          use-cross: ${{ matrix.job.use-cross }}
          cross-version: ${{ matrix.job.cross-version || 'from-source' }}
          project-dir: "native/explorer"
          cargo-args: ${{ matrix.job.cargo-args }}
          variant: ${{ matrix.job.variant }}

      - name: Artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: ${{ steps.build-crate.outputs.file-path }}

      - name: Artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build-crate.outputs.file-name }}
          path: ${{ steps.build-crate.outputs.file-path }}

      - name: Publish archives and packages
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.build-crate.outputs.file-path }}
        if: startsWith(github.ref, 'refs/tags/')
